project:
    name: tech-blog
    type: hexo

before_prepare:
    - command: '/usr/bin/npm install -g hexo'
    - command: '/usr/bin/npm install'
    - command: '/usr/local/bin/gulp styles'
    - command: '/usr/local/bin/hexo generate'

prepare:

config:

docker_template: "clean-default"

slack_channel: "#nodesengineeringblog"